name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PANEL_API_URL: ${{ vars.PANEL_API_URL }}
  PANEL_APPLICATION_KEY: ${{ vars.PANEL_APPLICATION_KEY }}
  PANEL_CLIENT_KEY: ${{ vars.PANEL_CLIENT_KEY }}
  DISCORD_TOKEN: ${{ vars.DISCORD_TOKEN }}
  DISCORD_CHANNEL: ${{ vars.DISCORD_CHANNEL }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "*.py" -v
    
    - name: Run linting
      run: |
        pylint **/*.py